### ISSUE TITLE
アンケート方式　で　認証キーと次の項目の間にスキマ

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/Questionnaires#142]
![127_0_0_1_9090_questionnaires_questionnaire_edit_edit_9_9b702a6b7e2866dd5f2bb14844ef0a4f_s_id_4da75c1b0903d7fa6633d381549a7790_frame_id_28](https://cloud.githubusercontent.com/assets/1955236/12343554/06a76ac2-bb78-11e5-8312-7642739064fa.png)

下記にすれば空かないです。（いいかどうかは微妙か）

```
					echo $this->QuestionEdit->questionnaireAttributeCheckbox('is_key_pass_use',
						__d('questionnaires', 'use key phrase'),
						array(
							'ng-disabled' => 'questionnaires.questionnaire.isImageAuthentication == ' . QuestionnairesComponent::USES_USE));
					echo $this->element('AuthorizationKeys.edit_form', [
						'options' => array(
							'div' => 'checkbox', // checkboxにすれば、スキマあかない
						'ng-show' => 'questionnaires.questionnaire.isKeyPassUse != 0',
					)]);
```

**Comment by RikaFujiwara** [comment]
すみません、画面全体見直しているうちに（これらチェックボックスはパブリックで非会員にも回答OKにしたときだけ出す、とか）いつの間にか治ってしまっていました。。。。
