### ISSUE TITLE
集計データの閲覧をするのに「回答済み」の状態は不要ではないか？

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/Questionnaires#23]
今までは集計データは、回答した人にしか見せない、という前提で作成していた。
これはＮＣ２がそうであったため、その仕様を継承しているイメージである。
ログインして回答している人間の場合は、ログインＩＤの一致で過去の回答状況を間違いなく探せるが
未ログインで回答している人間の場合はセッションＩＤで探しているため、セッションが時間切れになると同時に「今まで見れていた」集計データが突然見れなくなるという現象になる。
（Ｃａｋｅってセッションが時間で切り替わるのですかね？）

これはあまりよろしくない現象である（突然、エラー画面に連れていかれるので）
思い切って回答済みかどうかのチェックは集計データの閲覧権限から外した方がよいのではないかと考えています。

**Comment by RikaFujiwara** [comment]
寺口さんからヒントもらう

集計結果が常時みたいよ！というニーズがあるのは（かつ許していいのは）編集長（もしくは作成者）ではないか？
つまり、集計結果表示画面へのリンクを一覧の下の編集ボタン表示エリアにつけておけばいいのではないかとのこと。

この案いただきます

**Comment by kteraguchi** [comment]
すみません。
この案は、回答だけできる人は集計データが見れない前提ですよね。
回答だけできる人も集計は見れた方が良いと思ってます。

```
回答済みかどうかのチェックは集計データの閲覧権限から外した方がよいのではないかと考えています。
```

こっちが良いと思います。

ちょっとこっちで仕様の確認しますので、保留でお願いします。

ちなみに、Ｃａｋｅってセッション情報は、app\Config\application.ymlのSessionに記述されてます。

**Comment by RikaFujiwara** [comment]
>>回答済みかどうかのチェックは集計データの閲覧権限から外した方がよいのではないかと考えています。

>こっちが良いと思います。

ということは、未回答の人も回答前に集計結果を見ることができるようにすべき、とのことですか？

**Comment by kteraguchi** [comment]
べきという感じでもないです。
A派 vs B派みたいな2択で、世の中B派が多いみたいなサイトありますよね。
http://ecnavi.jp/vote/choice/1101/
http://www.dotchi.jp/
このイメージで、回答前に集計結果を見れても良いのかなぁと思ったのですが、
よくよく考えるとアンケートとはちょっと違いますね。別機能な感じです。

あと、
> 未ログインで回答している人間の場合はセッションＩＤで探しているため、セッションが時間切れになると同時に「今まで見れていた」集計データが突然見れなくなるという現象になる。
NC2もそうですが、これはやはり変かなと思っています。

集計結果の公開設定は3択では？と思ったり。
パターン１
　集計結果を公開しない
　　　編集権限がある人のみ集計結果を見れる（編集長とか）

パターン２
　回答した人に集計結果を公開する
　　　回答した人が集計結果を見れる
　　　非会員の回答OKの場合、このパターンはNG

パターン３
　集計結果を公開する
　　　未回答でも集計結果を見れる

現状のアンケート作成ウィザードだと、集計結果の公開設定後に、非会員の回答受付設定があるので、
ちょっと厳しいですね。
やっぱ、非会員はセッションで判断するので良い気もしてきました。

**Comment by to-hashimoto-3** [comment]
未ログイン（＝匿名）回答ＯＫとした作られたアンケートは、未ログインなのだから、（セッションが変われば）何回でもアンケート回答できます。
ＮＣ２の仕様（匿名回答者は、セッション期間中のみ集計が閲覧できる）でつくると、匿名者は、また再度匿名回答することで、集計結果を再び閲覧できるようになります。これは防ぎようがありません。

でも、匿名許可のアンケートを実施する人は、回答母数が１人１回自体が厳密にならないことを実施者自身が許容しているのだから、つまり、母数が曖昧性を許容していることになります。

アンケート実施者がアンケートの母数の厳密性を放棄（とまではいわなくても、厳密性をそれほどもとめていない）以上、
匿名回答者が、集計結果をみたくなって再び、匿名回答することで集計結果を見る行為も、許容しなければならないとおもいます。

つまり、、ＮＣ２の現仕様（匿名者は、セッション期間中のみ集計をみれる）が、落としどころとして、丁度よいかんじがします。（いきなり見れなくなった場合の違和感は、メッセージの文言で緩和するのが、ベターかな、、ぐらいです）

あるいは、集計結果は回答者には公開しないと最初からしておく、かいずれかですね。

ただし、未回答でも集計結果をみれるようにしておく（＝すべての回答者が集計結果をしって回答にのぞむ）
というのは、そもそもアンケートというようり、リアルタイム投票になってしまう気がする。

**Comment by kteraguchi** [comment]
確認したところ、現状で良いです。
　・非会員はセッションで判断
　・回答前に集計結果は見れない

> つまり、、ＮＣ２の現仕様（匿名者は、セッション期間中のみ集計をみれる）が、落としどころとして、丁度よいかんじがします。（いきなり見れなくなった場合の違和感は、メッセージの文言で緩和するのが、ベターかな、、ぐらいです）

まさに、それです！
ということで、Closeします。

**Comment by kteraguchi** [comment]
非会員の回答済み処理について、セッションで判断と言いましたが、Cookieの方が良いですね。

**Comment by RikaFujiwara** [comment]
回答済みかどうかの判断はセッションではなくCookie判断に賛成

**Comment by RikaFujiwara** [comment]
最終的に落ち着いた仕様

・非会員はセッションで判断
・回答前に集計結果は見れない
・集計結果を見てもいいかどうかの判断はCookieに「このアンケートは回答した」が残っているかどうか

**Comment by RikaFujiwara** [comment]
そもそもの問いかけ部分「アンケートの編集権限を持っている人は『集計表示ON』のアンケートの場合は、回答状況や集計表示期間の条件に関わらず、集計画面が見られる」は皆さん賛成と判断して修正します

なお、未ログイン者の閲覧制限をCookie云々は上記寺口さんが別途立ててくれたISSUEにて対応です

**Comment by RikaFujiwara** [comment]
48a6b6eb4ec296457d924cca36c186bfa9b6a924
