### ISSUE TITLE
javascriptエラー：ファイル: tinymce.min.js、行: 5、列: 13121

### ISSUE THREAD

**Issue by acosada** [NetCommons3/Questionnaires#27]
アンケート質問を作成時に、質問タイトルが記入できなくなり、ウィジウィグが表示されなくなった。
アンケートは3ページ作成。スキップロジックを設定。
エラーは下記
ファイル: tinymce.min.js、行: 5、列: 13121

**Comment by RikaFujiwara** [comment]
もしかしたらtinymceのバージョンアップによってでなくなったのではないでしょうか
もう一度同じ操作を試してください

**Comment by RikaFujiwara** [comment]
再現しなくなったのでいったんＣｌｏｓｅ
