### ISSUE TITLE
【急】phpwarningが出ました

### ISSUE THREAD

**Issue by acosada** [NetCommons3/Questionnaires#31]
アンケート作成時、質問作成からnextを押し、集計結果にいこうとしたら下記のwarningがでました。

Notice (8): Undefined offset: 2 [CORE/Cake/Utility/Hash.php, line 905]
Notice (8): Undefined offset: 3 [CORE/Cake/Utility/Hash.php, line 905]

もしかしたらスキップロジックがからんですかも。。
スキップロジックをちゃんと設定しても、設定されてないとエラーがでました。

**Comment by RikaFujiwara** [comment]
@ackiku
この件、もしかしたら
https://github.com/NetCommons3/Questionnaires/commit/4827015b76e332c61b83f383c13409e0abf96422
で解決したかも知れません
もう一度確認して、何事もなければCloseしてもらってよいですか？

**Comment by RikaFujiwara** [comment]
94db68332e50d441e6c6174f70702146d4400e22
こちらで解決
