### ISSUE TITLE
phpdocでエラー

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/Questionnaires#32]
https://travis-ci.org/NetCommons3/NetCommons3Docs/jobs/64190032#L2969

私の開発環境（本日（6/5）最新）のバージョンでも発生しています。修正お願いします。

**Comment by RikaFujiwara** [comment]
@s-nakajima
ただいま修正作業を行っています。ローカルの確認環境ではエラーをなくしていってますが、
上記エラーの確認はNetCommons3Docsリポジトリですね。
QuestionnairesをCommitしても、NetCommons3Docsのリポジトリが書き変わるわけではないので、
QuestionnaireCommit後、どうやってエラーが取れきったことを確認すればよいでしょうか？

**Comment by s-nakajima** [comment]
現在のバージョンをRestart buildしてください。
![default](https://cloud.githubusercontent.com/assets/4422735/8000835/52712dfa-0b9a-11e5-91fc-b7264653c4ef.PNG)

**Comment by RikaFujiwara** [comment]
すみません、そのアイコンはどこに表示されているのでしょうか
画面全体のキャプチャで教えてもらえませんか
Ｔｒａｖｉｓの画面をみてもそのようなアイコンが見つけられません。。。。。

**Comment by RikaFujiwara** [comment]
すみません
ログインしてませんでした
ログインしたら見つかりました

**Comment by RikaFujiwara** [comment]
bfbe5e0f0ee01869ff0bebea41de11cfec02382f
