### ISSUE TITLE
質問エラーを表示させた後、順序を入れ替えようとすると、おかしくなる

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/Questionnaires#4]
（質問タイトルを未入力エラー表示時）
![default](https://cloud.githubusercontent.com/assets/4422735/7963442/ae54979a-0a4d-11e5-8ef8-8ee6269edbcc.PNG)

（順序入れ替えようとする）
![default](https://cloud.githubusercontent.com/assets/4422735/7963460/c415a3e4-0a4d-11e5-8883-ac39b83ecb26.PNG)

**Comment by RikaFujiwara** [comment]
Javascript側で保持しているアンケートの質問データとエラーメッセージデータを別配列で管理しているために発生している。
解決案は２つある。
１．質問データの順番を変えたときに、エラーメッセージ側の順番も同じように入れ替える方法。
２．質問データのオブジェクトの中にエラーメッセージ情報も含めてしまい、質問データの並び替えで、自動的にエラーメッセージもくっついていくようにすること

２のほうが、今後のためによさそうな気がするので、２の方式でやれるか検討してみる

**Comment by RikaFujiwara** [comment]
https://github.com/NetCommons3/Questionnaires/commit/ae11b661f427e9916fe8b0c4b8a9bc94f1d946bd
エラーメッセージをそれぞれのデータ要素のオブジェクト内の１属性とする方法で対応
