### ISSUE TITLE
テストモード時のアンケート設定表示

### ISSUE THREAD

**Issue by ackiku** [NetCommons3/Questionnaires#51]
テストモード時はアンケートの繰り返し回答をチェックしなくても、繰り返し回答できるようにしたい。しかし、それでは繰り返しにチェックしてるかユーザーがわからなくなるのではないか。。
上記のいきさつから、テスト時は最初の画面にアンケート設定を表示することにした。
ワイヤーを作成したので、藤原さんに送付した

**Comment by RikaFujiwara** [comment]
![wire_](https://cloud.githubusercontent.com/assets/3078370/8180086/7e0ac51a-1456-11e5-871a-5bd1a78b85da.jpg)
