### ISSUE TITLE
ファイルのパーミッション

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Questionnaires#65]
ファイルのパーミッションが775になっているものがあります。
644が良いです。

**Comment by RikaFujiwara** [comment]
Windows git shellを使うとパーミッションが整えられてしまうみたいで、WindowsGitを使っているとこの件に対応できない
VagrantにCloneしてそこからやり直すようにする（2015/07/03現在　ローカルVagrantソースを壊せないので来週対処）
