### ISSUE TITLE
キーフレーズや画像認証について

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Questionnaires#66]
別プラグインにした方が良いですよね。

**Comment by kteraguchi** [comment]
現状、画像認証はNetCommonsプラグインにある。
キーフレーズは組み込み。

NetCommonsプラグイン内で共通機能とするものと、プラグイン化するものの区別が不明とのこと。

**Comment by RikaFujiwara** [comment]
画像認証を共通コンポーネントとして切り出すこと

**Comment by RikaFujiwara** [comment]
別ISSUEとして書きだすので、こちらのISSUEはCloseします
