### ISSUE TITLE
自分の回答内容確認

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Questionnaires#71]
この機能はあるのでしたでしょうか？

回答済みの処理にもかかわるかもです。
https://github.com/NetCommons3/Questionnaires/issues/23

**Comment by RikaFujiwara** [comment]
この機能はありません。
NC2ではありましたね。
３のアンケート設計をするときに、「アンケートの回答を見る」という機能は不要ではないですか？それは小テストの機能ですよね。と確認し、削除の方向を認めてもらったと記憶しています。

**Comment by kteraguchi** [comment]
了解です。
小テスト開発時検討ですね。
