### ISSUE TITLE
自分が作成者の場合はcontentEditable権限を持ってなくてもis_latestデータが見えなくてはならない

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/Questionnaires#73]

**Comment by kteraguchi** [comment]
現状での正しい条件はFAQのコードです。
https://github.com/NetCommons3/Faqs/blob/ccf42abb40cb5b20c6563cff69090843f823aaad/Controller/FaqQuestionsController.php#L272
＃ 「メソッド名はgetでしょ。」というのは、置いといてください。

共通化しときたい部分です。
https://github.com/NetCommons3/NetCommons/issues/31

**Comment by RikaFujiwara** [comment]
なるほど。
Faqのこの条件取得が基本形で、それからそれぞれのプラグインごとの条件が加わる感じですね。

共通化しときたい、ということはNetCommonsプラグインのBehaviorに新しいものが加わって、それを皆で使うというようなところでしょうか
だったらプラグイン側はもうちょっと待っていた方がいいのかな？
明日のもくもくで、この辺の作業計画を少しお話させてください

**Comment by RikaFujiwara** [comment]
共通のBehaviorが出てきてから対処を行うことに決定した（7/9）

**Comment by RikaFujiwara** [comment]
204d74dd77ab1ac1106109397f9bdcf82d490034
