### ISSUE TITLE
QuestionnairesController::indexアクションについて

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Questionnaires#75]
表示方法設定の一覧表示か1アンケート表示によって、処理を分けている部分ですが、
1アンケート表示の場合、requestActionを使用してQuestionnaireAnswersController::answerアクションを呼んでいます。

frame機能でrequestActionを使用しているのですが、できるだけrequestActionを使用しないほうが良いです。
＃ 遅くなるため。

もくもく会で相談させてください。

**Comment by RikaFujiwara** [comment]
ちょっと調べてみたのですが、複数コントローラで共通の動作を行わせたい場合は、Component化しないといけないようですね
AnswerControllerを別コントローラから呼び出せばいいじゃん、とか思ったんですが（完全に同一動作なので）
requestActionがそんなにも負荷高い処理である場合は共通コンポーネント作成に舵を切ろうと思います。

**Comment by RikaFujiwara** [comment]
framesテーブルにdefault_actionフィールドを付けることになった
アンケートはFrameSettingの処理で単独表示が選択された場合は、frameテーブルのdefault_actionの設定値をQuestionnaireAnswerControllerのviewに変更しておく！
それでこの部分は考えなくて済むようになる

**Comment by RikaFujiwara** [comment]
https://github.com/NetCommons3/Questionnaires/commit/64f7ea46ce575029091071cc5b18aee84ba984e3
