### ISSUE TITLE
回答数の処理について

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Questionnaires#78]
QuestionnairesController::indexアクションで、サブクエリーを使用して回答数を取得しています。
また、Questionnaire::afterFindで、改めて回答数を取得してます。
後者の処理だけで良いと思いますが、お試しの状態でしょうか？

**Comment by RikaFujiwara** [comment]
サブクエリーで取っている回答数は「自分が回答した数」で
AfterFindでとった回答数は自分のに限らず「現時点での全ての回答数」なのです

サブクエリーで取っている「自分が回答した数」は、アンケート一覧を絞り込むときに「回答済み」「未回答」のフィルタがあるために行っています。

自分が（未ログインでセッションIDしかない人でも）回答済なのかどうかを知るよい方法がサブクエリ以外に手段あればよいのですが。。。。良いアイデアありますか？

**Comment by kteraguchi** [comment]
了解しました。
回覧板でも自分が回答したかどうかの判断があるはずなので見てみます。

**Comment by kteraguchi** [comment]
回覧板見てみました。
CircularNoticeContent（回覧モデル）とCircularNoticeTargetUser（回答モデル）があります。
CircularNoticeContent hasMany CircularNoticeTargetUserで、一人一回答が前提です。

んで、MyCircularNoticeTargetUserというエイリアスでhasOneのアソシエーションを定義しています。
「My」を付けて、自分の回答データを取得するのがミソですね。
https://github.com/NetCommons3/CircularNotices/blob/847152225f973229cdbd5ef46cfb7c76283d1dbb/Model/CircularNoticeContent.php#L477

あとは、MyCircularNoticeTargetUserが回答済みかどうかをconditionとしてfindしています。

アンケートには利用できなそうですね。。。

**Comment by kteraguchi** [comment]
回覧板に寄せるなら、QuestionnaireAnswerUserモデルみたいなの作って、
Questionnaire hasOne QuestionnaireAnswerUserを定義する感じでしょうか。

**Comment by RikaFujiwara** [comment]
はい、そうですね。。。
アンケートは１アンケートに複数回答を許しちゃっているところが回覧板と異なります

単純な結合でFindするためには、user_id または session_idをプライマリキーにしたものを定義する感じになるしかないのかなーと行き詰っております

QuestionnaireAnswerUserはテーブルじゃなくてViewにしちゃうという手はあるのでしょうか
Viewにしたら結局　負荷が高くなるのでしょうかね

**Comment by kteraguchi** [comment]
Viewって、DBのViewですね？
CakePHPのViewかと思い混乱しました。

DBViewの利用は検討の余地ありですかね。
若かりし頃DBViewを利用した記憶があるくらいですが、どうなのでしょうか。
もくもく会であげてみましょう。

**Comment by kteraguchi** [comment]
件数取得処理について、他プラグインでも関係してますので、リンク貼っときます。
https://github.com/NetCommons3/ContentComments/issues/2

**Comment by RikaFujiwara** [comment]
絞込条件の中に、「特定条件にマッチした解答件数」を求めている点、
サブクエリを使うことで、扱うデータ量が少なくなる点、
サブクエリを使ったほうがロジックがすっきりする点
将来的にはＭｙＳＱＬのサブクエリ取り扱い性能が改善される可能性がある点
などから、サブクエリの使用はＯＫとなりました
これによりこのＩＳＳＵＥはＣｌｏｓｅとします
