### ISSUE TITLE
キーフレーズ認証機能を共通コンポーネントとして切り出して各プラグインが使いやすい形にすること

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/Questionnaires#87]

**Comment by kteraguchi** [comment]
キーフレーズ認証の名称が微妙な気がします。
他システムでキーフレーズと表現しているのでしょうか？
認証キーのような気がしますが、１個人を認証するわけでもないですし。。。
うーん良い名前がないです。

**Comment by RikaFujiwara** [comment]
204d74dd77ab1ac1106109397f9bdcf82d490034
